# Generated by Django 5.1.5 on 2025-02-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
