# Generated by Django 5.1.5 on 2025-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
