# Generated by Django 5.1.5 on 2025-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_slug_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
